version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    hostname: $MYSQL_HOST
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER

  app:
    build: ./front
    env_file: .env
    volumes:
      - ./front:/app/front
    ports:
      - '3000:3000'

  server:
    build: ./server
    env_file: .env
    volumes:
      - ./server:/app/server
    ports:
      - '3010:3010'

volumes: 
  db: